#!/usr/bin/env bash
# Script to display information about server subdomains

# Define a function to fetch and display DNS information for specified subdomains
get_dns_info() {
    # Check if subdomain argument is provided
    if [ -n "$2" ]; then
        # If subdomain argument is provided, query DNS for that specific subdomain
        dig "$2.$1" | grep -A1 'ANSWER SECTION:' | paste - - | awk -v sd="$2" '{print "The subdomain " sd " is a " $7 " record and points to " $8}'
    else
        # If no subdomain argument provided, query DNS for default subdomains
        dig "www.$1" | grep -A1 'ANSWER SECTION:' | paste - - | awk '{print "The subdomain www is a " $7 " record and points to " $8}'
        dig "lb-01.$1" | grep -A1 'ANSWER SECTION:' | paste - - | awk '{print "The subdomain lb-01 is a " $7 " record and points to " $8}'
        dig "web-01.$1" | grep -A1 'ANSWER SECTION:' | paste - - | awk '{print "The subdomain web-01 is a " $7 " record and points to " $8}'
        dig "web-02.$1" | grep -A1 'ANSWER SECTION:' | paste - - | awk '{print "The subdomain web-02 is a " $7 " record and points to " $8}'
    fi
}

# Call the function with domain and subdomain arguments
get_dns_info "$1" "$2"
