#!/usr/bin/env bash
# This script installs and configures HAProxy to distribute traffic
# between web-01 and web-02 using a round-robin algorithm.

# Install HAProxy.
sudo apt-get update
sudo apt-get install -y haproxy

# Enable HAProxy to start on boot.
sudo systemctl enable haproxy

# Configure HAProxy.
HAPROXY_CFG="/etc/haproxy/haproxy.cfg"
WEB_01_IP="ip_of_web-01"
WEB_02_IP="ip_of_web-02"

# Backup the original configuration file.
sudo cp $HAPROXY_CFG "${HAPROXY_CFG}.backup"

# Append configuration for load balancing.
cat << EOF | sudo tee -a $HAPROXY_CFG

# Define frontend
frontend http_front
   bind *:80
   stats uri /haproxy?stats
   default_backend http_back

# Define backend
backend http_back
   balance roundrobin
   server web-01 $WEB_01_IP:80 check
   server web-02 $WEB_02_IP:80 check
EOF

# Restart HAProxy to apply the changes.
sudo systemctl restart haproxy

echo "HAProxy has been configured to load balance between web-01 and web-02 using round-robin."
