#!/usr/bin/env bash
# 101-manage_my_process script

pid_file="/var/run/my_process.pid"
script="./manage_my_process"

start() {
    if [ -f "$pid_file" ]; then
        echo "manage_my_process is already running. Use restart to restart."
    else
        $script &
        echo $! > "$pid_file"
        echo "manage_my_process started"
    fi
}

stop() {
    if [ -f "$pid_file" ]; then
        pid=$(cat "$pid_file")
        kill "$pid"
        rm -f "$pid_file"
        echo "manage_my_process stopped"
    else
        echo "manage_my_process is not running."
    fi
}

restart() {
    stop
    start
    echo "manage_my_process restarted"
}

usage() {
    echo "Usage: $0 {start|stop|restart}"
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        usage
        exit 1
        ;;
esac

exit 0

