#!/usr/bin/env bash
# This script displays lines containing the word 'bash' to get the PID of the Bash process.

# shellcheck disable=SC2009
# Using ps and grep to find lines containing the word 'bash'
ps aux | grep bash

