#!/usr/bin/env bash
# This script displays messages based on loop iteration and associated numbers.

counter=1

while [ $counter -le 20 ]; do
    case $counter in
        4)
            echo "$counter and then bad luck from China"
            ;;
        9)
            echo "$counter and then bad luck from Japan"
            ;;
        17)
            echo "$counter and then bad luck from Italy"
            ;;
        *)
            echo $counter
            ;;
    esac

    ((counter++))
done

